name: SignOff Project CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo_sqlsrv, sqlsrv, json, mbstring, zip, xml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Update Composer lock file
      run: composer update

    - name: Install required packages
      run: |
        composer require monolog/monolog
        composer require guzzlehttp/guzzle
        composer require --dev phpunit/phpunit:"^9.0"

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Set permissions for vendor/bin/phpunit
      run: chmod +x vendor/bin/phpunit

    - name: Run PHP Lint
      run: find . -type f -name "*.php" -exec php -l {} \;

    - name: Run PHP Unit Tests
      run: vendor/bin/phpunit

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: pdo_sqlsrv, sqlsrv, json, mbstring, zip, xml

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
        enable-AzPSSession: true

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'calfire'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Restart Azure Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp restart --name 'calfire' --resource-group 'calfire_group'
